// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://shcitchcvgwwbbzeualh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNoY2l0Y2hjdmd3d2JiemV1YWxoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5NDk3ODAsImV4cCI6MjA2MjUyNTc4MH0._tLHBXu3qlidEgiHC4tR_jP_MNG8gSCIYvXaeG5rR9Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);